[workspace]
members = ["contracts/*"]
exclude = [".cargo", "target"]
resolver = "2"

[workspace.dependencies]
ink = { version = "5.0.0", default-features = false }
ink_e2e = "5.0.0"
hex = { version = "0.4", default-features = false }